---
# Setup certification for the DAOS server nodes

- name: Setup DAOS server certification
  hosts: daosfs  # Select the right group
  become: true   # Enable sudo
  gather_facts: no  # Skip gathering facts

  tasks:
    - name: Delete existing certs
      file:
        path: /etc/daos/certs
        state: absent

    - name: Recreate the certificates directory
      file:
        path: /etc/daos/certs
        state: directory
        owner: root
        group: root
        mode: '0755'
    
    - name: Recreate the client certificates directory
      file:
        path: /etc/daos/certs/clients
        state: directory
        owner: daos_server
        group: daos_server
        mode: '0755'

    - name: Copy and configure certificates
      block:
        - name: Copy DAOS CA certificate
          synchronize:
            src: /home/xmei/daosCA/certs/daosCA.crt  # <=== Update this path!!!
            dest: /etc/daos/certs/daosCA.crt

        - name: Copy DAOS server certificate
          synchronize:
            src: /home/xmei/daosCA/certs/server.crt
            dest: /etc/daos/certs/server.crt

        - name: Copy DAOS server key
          synchronize:
            src: /home/xmei/daosCA/certs/server.key
            dest: /etc/daos/certs/server.key

        - name: Copy DAOS agent certificate
          synchronize:
            src: /home/xmei/daosCA/certs/agent.crt
            dest: /etc/daos/certs/clients/agent.crt    # different loc here
            recursive: true

    - name: Set ownership
      block:
        - name: Set ownership for DAOS CA certificate
          file:
            path: /etc/daos/certs/daosCA.crt
            owner: daos_server
            group: daos_server

        - name: Set ownership for DAOS server certificate
          file:
            path: /etc/daos/certs/server.crt
            owner: daos_server
            group: daos_server

        - name: Set ownership for DAOS server key
          file:
            path: /etc/daos/certs/server.key
            owner: daos_server
            group: daos_server

        - name: Set ownership for DAOS agent certificate
          file:
            path: /etc/daos/certs/clients/agent.crt
            owner: daos_server
            group: daos_server

