# <p>
# As the system admin is taking over the IP address assignment, this playbook
#  does not apply to the JLab daosfs testbed anymore.
# </p>

---
- name: Set IPoIB addresses for DAOS servers.
  hosts: daos_server
  become: yes
  tasks:
    - name: set IPoIB addresses of ib1 and ib3
      block:
        - name: extract server idx
          set_fact:
            idx: "{{ inventory_hostname.split('daosfs')[1] | int }}"

        - name: calculate IPoIB addresses
          set_fact:
            ib1_address: "10.148.1.{{ (( idx | int * 2) - 1) | string }}"
            ib3_address: "10.148.1.{{ ( idx | int * 2) | string }}"

        - debug:
            msg: |
              "Host {{ inventory_hostname }}:
              IB1's address should be {{ ib1_address }}
              IB3's address should be {{ ib3_address }}"

        - name: set ips
          shell: "ip addr add {{ ib1_address }}/24 dev ib1 && ip addr add {{ ib3_address }}/24 dev ib3"
...
