---
- name: Restart daos_agent services
  hosts: daos_client
  become: yes
  tasks:
    - name: start daos_agent service
      systemd:
        name: daos_agent
        state: restarted
        daemon_reload: true
...

