---
- name: Stop daos_server service.
  hosts: daosfs
  become: true
  gather_facts: no
  tasks:
    - pause:
        seconds: 1
    - name: stop daos_server service
      systemd:
        name: daos_server
        state: stopped

- name: Stop daos_agent service.
  hosts: daos_client
  become: true
  gather_facts: no
  tasks:
    - pause:
        seconds: 1
    - name: stop daos_agent service
      systemd:
        name: daos_agent
        state: stopped
...

