---
- name: Copy files to destination hosts.
  hosts: daos_server # select the right group
  become: true  # enable sudo

  vars:
    local_file_path_prefix: "/home/xmei/daos_ansible_install/daos"   # Update this before use.

  tasks:
  - name: copy daos_server.yml
    synchronize:
      src: {{ local_file_path_prefix }}/daos_server.yml
      dest: /etc/daos/daos_server.yml
      group: daos_server   # preserve the ownership to daos_server:daos_server
      owner: daos_server

  - name: copy 95-daos.conf for multiple IPoIB IPs setting
    synchronize:
      src: {{ local_file_path_prefix }}/95-daos.conf
      dest: /etc/sysctl.d/95-daos.conf
      group: no
      owner: no
...

