{
 "title": "DAOS servers",
 "description": "Monitor the DAOS servers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "Hostname", "query": { "query": "label_values(instance)" } },
   { "name": "telem_port", "label": "Telemetry port", "query": "9191" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Exporter Status",
   "type": "state-timeline",
   "description": "Status of the daos_exporter. \"Down\" means port 9191 of the remote server is unreachable, while the server engines may in good states.",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "label_replace(up, \"hostname\", \"$1\", \"instance\", \"(daosfs.*):.*\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Server Statistics",
   "type": "stat",
   "description": "Total server and rank numbers in the system.",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)", "legendFormat": "Servers" },
    { "expr": "count(engine_rank)", "legendFormat": "Engines" }
   ]
  },
  {
   "title": "Server resident memory",
   "type": "timeseries",
   "description": "Amount of resident memory size in bytes.",
   "gridPos": { "h": 5, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace((sum by(instance) (process_resident_memory_bytes)), \"hostname\", \"$1\", \"instance\", \"(daosfs.*):.*\")",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Engine uptime",
   "type": "stat",
   "description": "Time since the engine became ready.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - engine_servicing_at {}",
     "legendFormat": "Rank-{{rank}}"
    }
   ]
  },
  {
   "title": "Write processing time",
   "type": "timeseries",
   "description": "Average RPC update/write processing time by host.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "label_replace(avg by(instance) (engine_io_latency_tgt_update), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-target_update"
    },
    {
     "expr": "label_replace(avg by(instance) (engine_io_latency_bio_update), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-bio_update"
    },
    {
     "expr": "label_replace(avg by(instance) (engine_io_latency_vos_update), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-vos_update"
    },
    {
     "expr": "label_replace(avg by(instance) (engine_io_latency_bulk_update), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-bulk_update"
    }
   ]
  },
  {
   "title": "Read processing time",
   "type": "timeseries",
   "description": "Average RPC fetch/read processing time by host.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "targets": [
    {
     "expr": "label_replace(avg by(instance) (engine_io_latency_bulk_fetch), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-bulk_fetch"
    },
    {
     "expr": "label_replace(avg by(instance) (engine_io_latency_bio_fetch), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-bio_fetch"
    },
    {
     "expr": "label_replace(avg by(instance) (engine_io_latency_vos_fetch), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}-vos_fetch"
    }
   ]
  },
  {
   "title": "Write bytes",
   "type": "timeseries",
   "description": "Total number of bytes read.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (engine_pool_xferred_update), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Read bytes",
   "type": "timeseries",
   "description": "Total number of bytes read.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (engine_pool_xferred_fetch), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{ hostname }}"
    }
   ]
  },
  {
   "title": "Write RPCs",
   "type": "timeseries",
   "description": "Total number of processed object RPCs.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (engine_pool_ops_update), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Read RPCs",
   "type": "timeseries",
   "description": "Total number of processed object RPCs.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (engine_pool_ops_fetch), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "NVMe write commands",
   "type": "timeseries",
   "description": "Number of write commands completed by to the controller.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (engine_nvme_commands_host_write_cmds), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "NVMe read commands",
   "type": "timeseries",
   "description": "Number of read commands completed by to the controller.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "targets": [
    {
     "expr": "label_replace(sum by(instance) (engine_nvme_commands_host_read_cmds), \"hostname\", \"$1\", \"instance\", \"(.*):.*\")",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  { "title": "Server node: $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }, "repeat": "host" },
  {
   "title": "Local ranks",
   "type": "stat",
   "description": "Ranks of current node",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "engine_rank{instance=\"$host:$telem_port\"}",
     "legendFormat": "$host"
    }
   ]
  },
  {
   "title": "OS threads",
   "type": "stat",
   "description": "Number of OS threads created. ",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_threads{instance=\"$host:$telem_port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVMe usage",
   "type": "gauge",
   "description": "Percentage of used NVMe capacity by disk PCIe addresses.",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " 100 - engine_nvme_reliability_avail_spare{instance=\"$host:$telem_port\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "NVMe erors",
   "type": "stat",
   "description": "Number of errors reported to the engine on different categories of commands.",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (engine_nvme_commands_read_errs{instance=\"$host:$telem_port\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum by(instance) (engine_nvme_commands_write_errs{instance=\"$host:$telem_port\"})",
     "legendFormat": "write"
    },
    {
     "expr": "sum by(instance) (engine_nvme_commands_unmap_errs{instance=\"$host:$telem_port\"})",
     "legendFormat": "unmap"
    },
    {
     "expr": "sum by(instance) (engine_nvme_commands_media_errs{instance=\"$host:$telem_port\"})",
     "legendFormat": "media"
    }
   ]
  },
  {
   "title": "Timeouts",
   "type": "stat",
   "description": "Total number of timed out requests.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (engine_net_uri_lookup_timeout{instance=\"$host:$telem_port\"})",
     "legendFormat": "URI lookup"
    },
    {
     "expr": "sum by(instance) (engine_net_req_timeout{instance=\"$host:$telem_port\"})",
     "legendFormat": "RPC"
    }
   ]
  },
  {
   "title": "Open file number",
   "type": "stat",
   "description": "Number of open files.",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$host:$telem_port\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Open file percentage",
   "type": "stat",
   "description": "Percentage of open files.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$host:$telem_port\"} / process_max_fds{instance=\"$host:$telem_port\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dead rank events",
   "type": "stat",
   "description": "Number of dead rank events received. ",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (instance) (engine_events_dead_ranks{instance=\"$host:$telem_port\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Grab buffer errors ",
   "type": "stat",
   "description": "Number of frab buffer errors.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (engine_dmabuff_grab_errs{instance=\"$host:$telem_port\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "NVMe disk temperature",
   "type": "timeseries",
   "description": "Current SSD temperature in Celsius.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg by(device) (engine_nvme_temp_current{instance=\"$host:$telem_port\"} - 273.15)",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}