# The inventory file for the DAOS file system.

[daosfs:children]
daos_server_1
daos_server_2

[daos_server_2]
daosfs0[1:4]

[daos_server_2]
daosfs0[5:8]

[daos_telem]
nvidarm-adm

[daos_admin]
nvidarm-adm
daosfs01
