---
- hosts: daos_server
  become: yes
  tasks:
    - name: stop daos_server service
      systemd:
        name: daos_server
        state: stopped

    - name: start daos_server service
      systemd:
        name: daos_server
        state: started
        daemon_reload: true
...

