---
- hosts: daos_server
  become: yes
  tasks:
    - name: stop daos_server service
      systemd:
        name: daos_server
        state: stopped

    - name: start daos_server service
      systemd:
        name: daos_server
        state: started
        daemon_reload: true

- hosts: daos_client
  become: yes
  tasks:
    - name: start daos_agent service
      systemd:
        name: daos_agent
        state: restarted
        daemon_reload: true
...

